#!/bin/sh

set -e  # stop script immediately on any error

echo "[*] Creating output folder if it doesn't exist..."
mkdir -p /semgrep_output

echo "[*] Running semgrep scan..."
semgrep --config=auto --json --output=/semgrep_output/results.json /code

if [ ! -s /semgrep_output/results.json ]; then
  echo "[!] No findings generated by Semgrep. Skipping upload to DefectDojo."
  exit 0
fi

echo "[*] Uploading results to DefectDojo..."
curl -X POST \
  -H "Authorization: Token $DEFECTDOJO_API_KEY" \
  -F "file=@/semgrep_output/results.json" \
  -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
  -F "scan_type=Semgrep JSON Report" \
  -F "active=true" \
  -F "verified=true" \
  $DEFECTDOJO_URL/api/v2/import-scan/


echo "[*] Done!"
  # -F "close_old_findings=false" \
  # -F "push_to_jira=true" \